//====================================================================================================
// Base code generated with LeatherGoods - ASF.Data
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data.Common;
using System.Data;
using System.Data.Entity;
using Microsoft.Practices.EnterpriseLibrary.Data;
using ASF.Entities;

namespace ASF.Data
{
    /// <summary>
    /// 
    /// </summary>
    public class CategoryDAC : AbstractDAC<Category>
    {

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void DeleteById(int id)
        {
            using (var dbc = createContext())
            {
                Category category = new Category { Id = id };
                dbc.Category.Attach(category);
                dbc.Category.Remove(category);
                dbc.SaveChanges();
            }
        }


        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>		
        public List<Category> Select()
        {

            return SelectAll(createContext());
            
        }
        
    }
}

